export const ROUTERS = {
    USER: {
        HOME: "",
        PRODUCT: "product",
        NEWS: "news",
        LOGIN: "login",
        REGISTER: "register",
        CHANGEPASSWORD: "changepassword",
        REQUESTINVOICE: "requestinvoice",
        YEUCAUHOANTRA: "requestrefund",
        PROFILE: "profile",
        INSURANCEREGISTRATION: "InsuranceRegistration",
        DONDANGKY: "registrationForms",
        REQUESTINVOICE: "requestinvoice",
        PAY: "pay",
        INVOICEHISTORYPAGE: "invoiceHistory",
        INVOICEHISTORYDETAILPAGE: "invoiceHistory/detail",

        STAFF: "staff",
        DONDANGKY: "registrationForms",
        TRANSACTION: "transactions",
        ADDINSPACK: "insurancePackManagement/add",
        INSURANCEPACKM: "insurancePackManagement",
        INFOCUSTOMER: "infoCustomer",
        FINANCIALREPORT: "financialReport",
    },
};
