export const ROUTERS = {
    USER: {
        HOME: "",
        PRODUCT: "product",
        NEWS: "news",
        LOGIN: "login",
        REGISTER: "register",
        STAFF: "staff",
        CHANGEPASSWORD: "changepassword",
        REQUESTINVOICE: "requestinvoice",
        DONDANGKY: "registrationForms",
        YEUCAUHOANTRA: "requestrefund",
        PERSONALINFO: "PersonalInfo",
        INSURANCEREGISTRATION: "InsuranceRegistration",
        DONDANGKY: "registrationForms",
        INSURANCEPACKM: "insurancePackManagement",
        ADDINSPACK: "insurancePackManagement/add",
        REQUESTINVOICE: "requestinvoice",
        HOADON: "invoice",
    },
};